# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fda773a5fd5e36b56e0c291bb97bd66c3c231a3f7946e79e3d42b5f007eff0e26eefa89b9b6f223fb546eb07619d4132722b57c7688f4475a2511ad82668224d

test:
  secret_key_base: 838264dd26db721824f8684cf25939f49c03a8d36d803bbf97b729298aca0557675df2e0132f529662d2156ccbe0cd80502e0bfabe67752e190f8632e6752c12

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
